# Generated by Django 5.1.6 on 2025-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("frequency", models.CharField(max_length=50)),
                ("day", models.IntegerField()),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
    ]
